<?php

namespace ContainerCtcg0hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1vN4qk6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vN4qk6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vN4qk6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminAlimentController::ajoutEtModif' => ['privates', '.service_locator.R_nMxvj', 'get_ServiceLocator_RNMxvjService', true],
            'App\\Controller\\AdminAlimentController::index' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController::alimentsAvecMoinsGlucides' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController::alimentsMoinsCaloriques' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController::index' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminAlimentController:ajoutEtModif' => ['privates', '.service_locator.R_nMxvj', 'get_ServiceLocator_RNMxvjService', true],
            'App\\Controller\\AdminAlimentController:index' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController:alimentsAvecMoinsGlucides' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController:alimentsMoinsCaloriques' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'App\\Controller\\AlimentController:index' => ['privates', '.service_locator.FjAj_le', 'get_ServiceLocator_FjAjLeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminAlimentController::ajoutEtModif' => '?',
            'App\\Controller\\AdminAlimentController::index' => '?',
            'App\\Controller\\AlimentController::alimentsAvecMoinsGlucides' => '?',
            'App\\Controller\\AlimentController::alimentsMoinsCaloriques' => '?',
            'App\\Controller\\AlimentController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminAlimentController:ajoutEtModif' => '?',
            'App\\Controller\\AdminAlimentController:index' => '?',
            'App\\Controller\\AlimentController:alimentsAvecMoinsGlucides' => '?',
            'App\\Controller\\AlimentController:alimentsMoinsCaloriques' => '?',
            'App\\Controller\\AlimentController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
