<?php

namespace ContainerCtcg0hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AlimentType' shared autowired service.
     *
     * @return \App\Form\AlimentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AlimentType.php';

        return $container->privates['App\\Form\\AlimentType'] = new \App\Form\AlimentType();
    }
}
